### PR TITLE
Fix to setup WAY_MASK_E51_ICACHE

### PR DESCRIPTION
**Pull request by atroger**
I think there is an error in the config_l2_cache function. 
WAY_MASK_E51_ICACHE is never set and WAY_MASK_E51_DCACHE is set twice.

### CODE REVIEW

**Comment by mallynch** [comment]
Antoinin, Thanks for pointing this out. Will are updating internally first and will push change.

**Comment by Cyril-Jean** [comment]
Malachy,
You will need to apply this change manually internally as the internal repo has moved forward for this specific code.

**Comment by mallynch** [comment]
This fix was implemented manually and is included in the src/platform/mpfs_hal directory currently on master.
Please note: Some of the example projects are not updated with this fix, planned updates of all example projects in the next two weeks.

**Comment by nitindeshpande** [comment]
The fix is available on [platform](https://github.com/polarfire-soc/platform)

**Pull request closed without merging**
